# HTTP Server
server:
  port: 8888

spring:
  application:
    name: ConfigServer
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL}
          searchPaths: ryanair, others

  # Spring properties in case you use different profiles
  profiles:
    active: dev
