# HTTP Server
server:
  name: ConfigServer
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL}

  # Spring properties in case you use different profiles
  profiles:
    active: dev
